sudo: false

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache

language: scala

scala:
  - 2.11.12
  - 2.12.7

jdk:
  - openjdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION test mimaReportBinaryIssues

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -exec rm {} +
  - find $HOME/.ivy2 -name "ivydata-*.properties" -exec rm {} +
